import { Metadata } from 'next'
import Link from 'next/link'
import LoftCalc from './LoftCalc'

export const metadata: Metadata = {
  title: 'Loft Conversion Cost Calculator London | Dwellinger',
  description: 'Calculate the cost of a loft conversion in London or the South East. Velux, dormer, L-shaped, mansard and hip-to-gable — with or without en-suite.',
}

export default function LoftCalculatorPage() {
  return (
    <main>
      {/* Hero */}
      <section style={{ backgroundColor: '#1A2340', color: '#FFFFFF', padding: '80px 24px', textAlign: 'center' }}>
        <div style={{ maxWidth: '720px', margin: '0 auto' }}>
          <p style={{ color: '#C4773B', fontWeight: 600, fontSize: '14px', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: '16px' }}>
            Free Tool
          </p>
          <h1 style={{ fontSize: 'clamp(1.8rem, 4.5vw, 2.9rem)', fontWeight: 700, lineHeight: 1.15, marginBottom: '16px' }}>
            Loft Conversion Cost Calculator
          </h1>
          <p style={{ fontSize: '1.1rem', color: '#c8d0de', maxWidth: '560px', margin: '0 auto', lineHeight: 1.6 }}>
            Velux, dormer, L-shaped, mansard — get an instant cost range for your loft conversion across London and the South East.
          </p>
        </div>
      </section>

      {/* Calculator (client component) */}
      <LoftCalc />

      {/* Loft types explainer */}
      <section style={{ backgroundColor: '#FFFFFF', padding: '64px 24px' }}>
        <div style={{ maxWidth: '1060px', margin: '0 auto' }}>
          <h2 style={{ color: '#1A2340', fontSize: 'clamp(1.4rem, 2.5vw, 1.9rem)', fontWeight: 700, textAlign: 'center', marginBottom: '40px' }}>
            Which Loft Conversion Type Is Right for Your Home?
          </h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '20px' }}>
            {[
              {
                type: 'Velux',
                cost: '£30k – £45k',
                best: 'Where roof pitch already provides headroom',
                note: 'Least disruptive. Usually permitted development.',
              },
              {
                type: 'Dormer',
                cost: '£45k – £65k',
                best: 'Most terraced and semi-detached homes',
                note: 'Most popular type. Good value for floor area gained.',
              },
              {
                type: 'L-shaped',
                cost: '£55k – £80k',
                best: 'Victorian and Edwardian terraces with rear return',
                note: 'Maximises floor area on properties with existing back additions.',
              },
              {
                type: 'Mansard',
                cost: '£75k – £100k',
                best: 'Where maximum floor area is required',
                note: 'Usually requires planning permission. Best for period properties.',
              },
              {
                type: 'Hip-to-gable',
                cost: '£40k – £60k',
                best: 'End-of-terrace and semi-detached homes',
                note: 'Extends one end to create more usable volume.',
              },
            ].map((item) => (
              <div key={item.type} style={{ padding: '24px', borderRadius: '8px', border: '1px solid #EDE8DC' }}>
                <h3 style={{ color: '#1A2340', fontWeight: 700, fontSize: '1.05rem', marginBottom: '6px' }}>{item.type}</h3>
                <p style={{ color: '#C4773B', fontWeight: 700, fontSize: '0.95rem', marginBottom: '10px' }}>{item.cost}</p>
                <p style={{ color: '#4A5568', fontSize: '0.87rem', lineHeight: 1.55, marginBottom: '6px' }}>
                  <strong>Best for:</strong> {item.best}
                </p>
                <p style={{ color: '#4A5568', fontSize: '0.87rem', lineHeight: 1.55, margin: 0 }}>{item.note}</p>
              </div>
            ))}
          </div>
          <p style={{ color: '#4A5568', fontSize: '0.82rem', textAlign: 'center', marginTop: '28px' }}>
            South East base costs shown. Inner London adds approx 20%, Outer London adds approx 10%.
          </p>
        </div>
      </section>

      {/* CTA */}
      <section style={{ backgroundColor: '#1A2340', padding: '64px 24px', textAlign: 'center' }}>
        <div style={{ maxWidth: '580px', margin: '0 auto' }}>
          <h2 style={{ color: '#FFFFFF', fontWeight: 700, fontSize: 'clamp(1.4rem, 3vw, 1.9rem)', marginBottom: '14px' }}>
            Ready for a Detailed Estimate?
          </h2>
          <p style={{ color: '#c8d0de', fontSize: '1rem', marginBottom: '28px', lineHeight: 1.6 }}>
            Our professional estimate service starts from £95 and is reviewed by a qualified QS — not generated by an algorithm.
          </p>
          <Link
            href="/services/estimating"
            style={{
              display: 'inline-block',
              backgroundColor: '#C4773B',
              color: '#FFFFFF',
              padding: '14px 36px',
              borderRadius: '6px',
              fontWeight: 700,
              fontSize: '1rem',
              textDecoration: 'none',
            }}
          >
            Get a Professional Estimate from £95
          </Link>
        </div>
      </section>
    </main>
  )
}
